www:
  image: nginx
  ports:
  - "8095:80"
  volumes:
  - data/store:/usr/share/nginx/html

ftp:
  build: ftp
  ports:
  - "21:21"
  - "2000:2000"
  - "2001:2001"
  - "2002:2002"
  - "2003:2003"
  - "2004:2004"
  - "2005:2005"
  volumes:
  - data/store:/var/www
  - data/credentials:/etc/vsftpd

sftp:
  image: atmoz/sftp
  volumes:
  - ./data/store:/home/$(USER)/store
  ports:
  - "2222:22"
  command: $(USER):$(PASSWORD):1000
