www:
  image: nginx
  ports:
  - "8095:80"
  volumes:
  - data/store:/usr/share/nginx/html

ftp:
  build: ftp
  ports:
  - "21:21"
  - "20:20"
  volumes:
  - data/store:/var/www
  - data/credentials:/etc/vsftpd

sftp:
  image: atmoz/sftp
  volumes:
  - ./data/store:/home/$(USER)/store
  ports:
  - "2222:22"
  command: $(USER):$(PASSWORD):1000
